"use client";

import { useState, useEffect, useRef, useCallback } from "react";

interface NewsItem {
  id: string;
  category: string;
  image: string;
  title: string;
  author: string;
  date: string;
  excerpt: string;
  fullText: string;
}

const newsData: NewsItem[] = [
  {
    id: "1",
    category: "Crypto",
    image: "https://images.unsplash.com/photo-1621416848440-236914c7467e?w=800&q=80&auto=format&fit=crop",
    title: "Vitalik Buterin Claims Some L2s are 'Economically Useless'",
    author: "Sarah Chen",
    date: "Feb 6, 2026",
    excerpt: "Ethereum's co-founder warns that without proper decentralization, Layer 2 solutions are just glorified databases.",
    fullText: "In a provocative blog post, Vitalik Buterin argued that many current Layer 2 solutions fail to provide the security guarantees that justify their existence. He emphasized that for an L2 to be truly valuable, it must reach 'Stage 2' decentralization, where security is enforced by code rather than multisigs. The comments have sent shockwaves through the scaling ecosystem, forcing projects to re-evaluate their roadmaps toward true trustlessness."
  },
  {
    id: "2",
    category: "Markets",
    image: "https://images.unsplash.com/photo-1611974710178-687a0c70f1fc?w=800&q=80&auto=format&fit=crop",
    title: "Silicon Valley's $700bn Question: Where is the AI ROI?",
    author: "Michael Zhang",
    date: "Feb 5, 2026",
    excerpt: "Investors are growing restless as the massive capital expenditure in AI fails to yield immediate profit margins.",
    fullText: "After two years of frantic investment, the tech world is facing a reckoning. The 'Silicon Valley $700bn Question' refers to the gap between the staggering cost of building GPU clusters and the actual revenue generated by generative AI features. While Big Tech continues to double down, analysts warn that the next earnings season could be a 'show me the money' moment for AI pioneers like Microsoft and Meta."
  },
  {
    id: "3",
    category: "Markets",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
    title: "Are Meta and Google Ads Truly Recession-Proof?",
    author: "Emma Watson",
    date: "Feb 4, 2026",
    excerpt: "New data suggests that even digital advertising giants are seeing a shift in corporate marketing appetites.",
    fullText: "Historically, digital ads were the last thing to be cut in a downturn. However, a new report suggests that the dominance of Meta and Google is being challenged by Amazon's retail media and Netflix's ad tier. As global economic headwinds persist, the narrative of 'unbreakable' digital ad growth is being tested, with prediction markets currently split on whether ad-revenue growth will hit double digits in 2026."
  },
  {
    id: "4",
    category: "Politics",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80&auto=format&fit=crop",
    title: "AI Is Not the Only Threat Menacing Big Tech",
    author: "James Park",
    date: "Feb 3, 2026",
    excerpt: "Antitrust scrutiny and data privacy laws are closing in on the giants faster than algorithmic competitors.",
    fullText: "While the media focuses on LLMs, the real danger for Big Tech may be the global wave of regulation. From the EU's Digital Markets Act to renewed US antitrust trials, the structural advantages of companies like Apple and Amazon are under siege. Prediction markets have seen a 20% spike in 'Breakup' scenarios for at least one major tech firm before the 2027 elections."
  },
  {
    id: "5",
    category: "Entertainment",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80&auto=format&fit=crop",
    title: "NASA Seeks Industry Input for SOLAR X-Ray Irradiance Sensors",
    author: "David Kim",
    date: "Feb 2, 2026",
    excerpt: "The space agency opens bidding for new sensor tech to monitor solar flares and protect satellite infrastructure.",
    fullText: "NASA has officially issued a request for information (RFI) for next-generation Solar X-Ray Irradiance Sensors. These devices are critical for 'Space Weather' monitoring, providing early warnings for solar storms that can knock out GPS, power grids, and satellite communications. The move signals a major push toward privatizing key components of solar observation infrastructure."
  },
  {
    id: "6",
    category: "Crypto",
    image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800&q=80&auto=format&fit=crop",
    title: "Stablecoin Dominance: Is USDC Finally Flipping USDT?",
    author: "Alex Rivera",
    date: "Feb 1, 2026",
    excerpt: "Compliance-first stablecoins see massive growth as regulatory clarity emerges in major financial hubs.",
    fullText: "New data shows USDC market share in Europe and Singapore has reached an all-time high, narrowing the gap with Tether. As the MiCA regulation takes full effect in the EU, the 'compliance-first' approach of Circle appears to be winning over institutional liquidity. Prediction markets are currently pricing a 35% chance that USDC total supply will exceed USDT by year-end."
  },
  {
    id: "7",
    category: "Politics",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=800&q=80&auto=format&fit=crop",
    title: "The Geopolitics of Semiconductors: TSMC's 2nm Gamble",
    author: "Lin Wei",
    date: "Feb 7, 2026",
    excerpt: "As Taiwan prepares for next-gen chip production, global powers race to secure supply chain dominance.",
    fullText: "TSMC is accelerating its 2nm production timeline, a move that is as much political as it is technical. With the world's dependence on high-end silicon reaching critical levels, the 'silicon shield' theory is being tested. Major economies are pouring billions into domestic foundries, but analysts question if anyone can truly replicate the efficiency of the Hsinchu science park."
  },
  {
    id: "8",
    category: "Entertainment",
    image: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=800&q=80&auto=format&fit=crop",
    title: "Streaming Wars 2.0: The Return of the Bundle",
    author: "Jordan Smith",
    date: "Feb 7, 2026",
    excerpt: "Fragmented markets lead to consumer fatigue, forcing rivals into unexpected alliances.",
    fullText: "In a surprising pivot, major streaming rivals are re-bundling their services, effectively recreating the cable TV packages they once sought to destroy. Disney, Warner Bros, and Netflix have announced cross-platform subscriptions to reduce churn and combat the rising cost of content production. It's a survival move in a saturated market where attention is the scarcest resource."
  }
];

// Newspaper style: bordered badges with subtle colors
const categoryColors: Record<string, { border: string; text: string; bg: string }> = {
  Crypto: { border: "border-violet-300", text: "text-violet-700", bg: "bg-white" },
  Markets: { border: "border-sky-300", text: "text-sky-700", bg: "bg-white" },
  Sports: { border: "border-orange-300", text: "text-orange-700", bg: "bg-white" },
  Entertainment: { border: "border-pink-300", text: "text-pink-700", bg: "bg-white" },
  Politics: { border: "border-sky-300", text: "text-sky-700", bg: "bg-white" },
};

export function NewsCarousel() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [flippedCards, setFlippedCards] = useState<Set<number>>(new Set());
  const [isMobile, setIsMobile] = useState(false);
  const deckRef = useRef<HTMLDivElement>(null);

  // Track screen size for responsive distance
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const nextCard = useCallback(() => {
    setCurrentIndex((prev) => (prev + 1) % newsData.length);
  }, []);

  const prevCard = useCallback(() => {
    setCurrentIndex((prev) => (prev - 1 + newsData.length) % newsData.length);
  }, []);

  const goToCard = useCallback((index: number) => {
    setCurrentIndex(index);
  }, []);

  const toggleFlip = useCallback((index: number) => {
    if (index === currentIndex) {
      setFlippedCards((prev) => {
        const next = new Set(prev);
        if (next.has(index)) {
          next.delete(index);
        } else {
          next.add(index);
        }
        return next;
      });
    }
  }, [currentIndex]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") prevCard();
      if (e.key === "ArrowRight") nextCard();
      if (e.key === " ") {
        e.preventDefault();
        toggleFlip(currentIndex);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [currentIndex, nextCard, prevCard, toggleFlip]);

  // Touch/drag handling with passive: false to prevent horizontal scroll
  useEffect(() => {
    const deck = deckRef.current;
    if (!deck) return;

    let touchStartX = 0;
    let touchStartY = 0;
    let isDraggingHorizontal = false;

    const handleTouchStart = (e: TouchEvent) => {
      touchStartX = e.touches[0].clientX;
      touchStartY = e.touches[0].clientY;
      isDraggingHorizontal = false;
    };

    const handleTouchMove = (e: TouchEvent) => {
      const diffX = e.touches[0].clientX - touchStartX;
      const diffY = e.touches[0].clientY - touchStartY;

      // If horizontal movement is greater, prevent default to stop page scroll
      if (Math.abs(diffX) > Math.abs(diffY) && Math.abs(diffX) > 10) {
        e.preventDefault();
        isDraggingHorizontal = true;
      }
    };

    const handleTouchEnd = (e: TouchEvent) => {
      const diffX = e.changedTouches[0].clientX - touchStartX;
      const diffY = e.changedTouches[0].clientY - touchStartY;

      if (isDraggingHorizontal) {
        // Swipe left (negative diff) = show next card
        if (diffX < -50) {
          nextCard();
        } else if (diffX > 50) {
          prevCard();
        }
      } 
      // If it was a tap (not a significant swipe or scroll)
      else if (Math.abs(diffX) < 10 && Math.abs(diffY) < 10) {
        const rect = deck.getBoundingClientRect();
        const tapX = e.changedTouches[0].clientX - rect.left;
        const centerX = rect.width / 2;
        const threshold = rect.width * 0.2; // 20% of width from center

        if (tapX < centerX - threshold) {
          prevCard();
        } else if (tapX > centerX + threshold) {
          nextCard();
        }
      }
      isDraggingHorizontal = false;
    };

    // Add listeners with passive: false for touch events
    deck.addEventListener("touchstart", handleTouchStart, { passive: true });
    deck.addEventListener("touchmove", handleTouchMove, { passive: false });
    deck.addEventListener("touchend", handleTouchEnd, { passive: true });

    return () => {
      deck.removeEventListener("touchstart", handleTouchStart);
      deck.removeEventListener("touchmove", handleTouchMove);
      deck.removeEventListener("touchend", handleTouchEnd);
    };
  }, [nextCard, prevCard]);

  // Mouse drag handling
  const mouseStartX = useRef(0);

  const handleMouseDown = (e: React.MouseEvent) => {
    mouseStartX.current = e.clientX;
  };

  const handleMouseUp = (e: React.MouseEvent) => {
    const diff = e.clientX - mouseStartX.current;
    
    // If it was a drag/swipe
    if (Math.abs(diff) > 50) {
      if (diff > 0) prevCard();
      else nextCard();
    } 
    // If it was a simple click, check if it was on the left or right "zones"
    else {
      const rect = deckRef.current?.getBoundingClientRect();
      if (rect) {
        const clickX = e.clientX - rect.left;
        const centerX = rect.width / 2;
        // Threshold: clicking further than 100px (mobile) or 150px (desktop) from center triggers navigation
        const threshold = isMobile ? 80 : 140;

        if (clickX < centerX - threshold) {
          prevCard();
        } else if (clickX > centerX + threshold) {
          nextCard();
        }
      }
    }
  };

  const getCardStyle = (index: number) => {
    const offset = index - currentIndex;
    const total = newsData.length;

    // Handle wrapping for smooth circular navigation
    let adjustedOffset = offset;
    if (offset > total / 2) adjustedOffset = offset - total;
    if (offset < -total / 2) adjustedOffset = offset + total;

    const angleStep = 360 / total;
    const angle = adjustedOffset * angleStep;
    // Responsive distance: smaller on mobile to keep cards visible
    const distance = isMobile ? 160 : 350;

    const x = Math.sin((angle * Math.PI) / 180) * distance;
    const z = Math.cos((angle * Math.PI) / 180) * distance - distance;
    const rotateY = -angle;

    let scale = 1;
    let opacity = 1;
    let zIndex = 0;

    const absOffset = Math.abs(adjustedOffset);
    if (absOffset === 0) {
      scale = 1;
      opacity = 1;
      zIndex = 10;
    } else if (absOffset === 1) {
      scale = isMobile ? 0.85 : 0.9;
      opacity = isMobile ? 0.7 : 0.85;
      zIndex = 5;
    } else if (absOffset === 2) {
      scale = isMobile ? 0.7 : 0.8;
      opacity = isMobile ? 0.5 : 0.65;
      zIndex = 3;
    } else {
      scale = isMobile ? 0.6 : 0.7;
      opacity = isMobile ? 0.3 : 0.5;
      zIndex = 1;
    }

    return {
      transform: `translate(-50%, -50%) translateX(${x}px) translateZ(${z}px) rotateY(${rotateY}deg) scale(${scale})`,
      opacity,
      zIndex,
    };
  };

  return (
    <div className="relative overflow-visible">
      {/* Carousel Container */}
      <div
        className="relative h-[460px] sm:h-[520px] md:h-[580px] mx-auto max-w-full overflow-visible"
        style={{
          perspective: "1200px",
          touchAction: "pan-y", // Allow vertical scroll, prevent horizontal
        }}
      >
        <div
          ref={deckRef}
          className="relative w-full h-full cursor-grab active:cursor-grabbing"
          style={{ transformStyle: "preserve-3d" }}
          onMouseDown={handleMouseDown}
          onMouseUp={handleMouseUp}
        >
          {newsData.map((news, index) => {
            const style = getCardStyle(index);
            const isFlipped = flippedCards.has(index);
            const isCurrent = index === currentIndex;
            const cat = categoryColors[news.category] || { border: "border-stone-300", text: "text-stone-700", bg: "bg-white" };

                                        return (

                                          <div

                                            key={news.id}

                                            className="absolute left-1/2 top-1/2 w-[260px] h-[400px] sm:w-[320px] sm:h-[460px] md:w-[400px] md:h-[500px]"

                                            style={{

                                              ...style,

                                              transformStyle: "preserve-3d",

                                              transition: "all 0.6s cubic-bezier(0.4, 0, 0.2, 1)",

                                              pointerEvents: "auto",

                                              cursor: isCurrent ? "pointer" : "zoom-in",

                                            }}

                                            onClick={(e) => {

                                              // Only handle flipping here if it's the current card

                                              if (isCurrent) {

                                                e.stopPropagation();

                                                toggleFlip(index);

                                              }

                                              // Otherwise, the event bubbles up to handleMouseUp for navigation

                                            }}

                                          >                {/* Card Inner (handles flip) */}
                <div
                  className="relative w-full h-full"
                  style={{
                    transformStyle: "preserve-3d",
                    transition: "transform 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
                    transform: isFlipped ? "rotateY(180deg)" : "rotateY(0deg)",
                  }}
                >
                  {/* Front Face */}
                  <div
                    className="absolute inset-0 overflow-hidden bg-white border border-stone-200"
                    style={{
                      backfaceVisibility: "hidden",
                      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
                    }}
                  >
                    <div className="p-5 sm:p-6 flex flex-col h-full">
                      <span className={`self-start px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider border ${cat.border} ${cat.text} ${cat.bg}`}>
                        {news.category}
                      </span>
                      <img
                        src={news.image}
                        alt={news.title}
                        className="w-full h-40 sm:h-44 md:h-48 object-cover mt-4"
                      />
                      <h3
                        className="text-xl sm:text-2xl font-serif font-semibold text-stone-900 mt-4 leading-tight line-clamp-2"
                      >
                        {news.title}
                      </h3>
                      <div className="flex items-center gap-2 mt-3 text-sm text-stone-500">
                        <span className="font-medium">{news.author}</span>
                        <span>•</span>
                        <span>{news.date}</span>
                      </div>
                      <p className="text-sm text-stone-600 mt-3 line-clamp-2 flex-1 leading-relaxed">
                        {news.excerpt}
                      </p>
                      <span className="text-xs text-[#0C4A6E] font-semibold mt-3">
                        Click to read more →
                      </span>
                    </div>
                  </div>

                  {/* Back Face */}
                  <div
                    className="absolute inset-0 overflow-hidden bg-white border border-stone-200"
                    style={{
                      backfaceVisibility: "hidden",
                      transform: "rotateY(180deg)",
                      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
                    }}
                  >
                    <div className="p-5 sm:p-6 flex flex-col h-full bg-[#FAFAF9]/50">
                      <div className="flex items-center gap-2 mb-4">
                        <span className={`px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider border ${cat.border} ${cat.text} bg-white`}>
                          Full Story
                        </span>
                        <span className="text-[10px] font-medium text-stone-400 uppercase tracking-widest">
                          Pulse Editorial
                        </span>
                      </div>
                      
                      <h3
                        className="text-xl sm:text-2xl font-serif font-semibold text-stone-900 leading-tight mb-4 border-b border-stone-200 pb-4"
                      >
                        {news.title}
                      </h3>
                      
                      <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar">
                        <p className="text-sm sm:text-base text-stone-700 leading-relaxed font-serif italic">
                          "{news.fullText}"
                        </p>
                      </div>
                      
                      <div className="flex items-center justify-between mt-4 pt-4 border-t border-stone-200">
                        <div className="flex flex-col">
                          <span className="text-[10px] font-medium text-stone-400 uppercase tracking-wider">Author</span>
                          <span className="text-xs font-semibold text-stone-900">{news.author}</span>
                        </div>
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleFlip(index);
                          }}
                          className="text-xs text-[#0C4A6E] font-semibold hover:underline"
                        >
                          ← Close
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Hint text */}
      <p className="text-center text-xs text-stone-400 mt-3">
        Swipe, drag, or use arrow keys to navigate
      </p>
    </div>
  );
}
