"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";

interface NewsItem {
  id: string;
  category: string;
  image: string;
  title: string;
  author: string;
  date: string;
  excerpt: string;
  fullText: string;
  url: string;
  source: string;
}

const newsData: NewsItem[] = [
  {
    id: "1",
    category: "Crypto",
    image: "/carousel/vitalik.jpg",
    title: "Vitalik Buterin Claims Some L2s are 'Economically Useless'",
    author: "Sarah Chen",
    date: "Feb 6, 2026",
    excerpt: "Ethereum's co-founder warns that without proper decentralization, Layer 2 solutions are just glorified databases.",
    fullText: "In a provocative blog post, Vitalik Buterin argued that many current Layer 2 solutions fail to provide the security guarantees that justify their existence. He emphasized that for an L2 to be truly valuable, it must reach 'Stage 2' decentralization, where security is enforced by code rather than multisigs. The comments have sent shockwaves through the scaling ecosystem, forcing projects to re-evaluate their roadmaps toward true trustlessness.",
    url: "https://vitalik.eth.limo/general/2023/10/31/l2_decentralization.html",
    source: "Vitalik.eth"
  },
  {
    id: "2",
    category: "Markets",
    image: "/carousel/ai-roi.jpg",
    title: "Silicon Valley's $700bn Question: Where is the AI ROI?",
    author: "Michael Zhang",
    date: "Feb 5, 2026",
    excerpt: "Investors are growing restless as the massive capital expenditure in AI fails to yield immediate profit margins.",
    fullText: "After two years of frantic investment, the tech world is facing a reckoning. The 'Silicon Valley $700bn Question' refers to the gap between the staggering cost of building GPU clusters and the actual revenue generated by generative AI features. While Big Tech continues to double down, analysts warn that the next earnings season could be a 'show me the money' moment for AI pioneers like Microsoft and Meta.",
    url: "https://www.economist.com/finance-and-economics/2024/07/02/the-700bn-question-facing-ai",
    source: "The Economist"
  },
  {
    id: "3",
    category: "Markets",
    image: "/carousel/google-meta.jpg",
    title: "Are Meta and Google Ads Truly Recession-Proof?",
    author: "Emma Watson",
    date: "Feb 4, 2026",
    excerpt: "New data suggests that even digital advertising giants are seeing a shift in corporate marketing appetites.",
    fullText: "Historically, digital ads were the last thing to be cut in a downturn. However, a new report suggests that the dominance of Meta and Google is being challenged by Amazon's retail media and Netflix's ad tier. As global economic headwinds persist, the narrative of 'unbreakable' digital ad growth is being tested, with prediction markets currently split on whether ad-revenue growth will hit double digits in 2026.",
    url: "https://www.ft.com/companies/technology",
    source: "Financial Times"
  },
  {
    id: "4",
    category: "Politics",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80&auto=format&fit=crop",
    title: "AI Is Not the Only Threat Menacing Big Tech",
    author: "James Park",
    date: "Feb 3, 2026",
    excerpt: "Antitrust scrutiny and data privacy laws are closing in on the giants faster than algorithmic competitors.",
    fullText: "While the media focuses on LLMs, the real danger for Big Tech may be the global wave of regulation. From the EU's Digital Markets Act to renewed US antitrust trials, the structural advantages of companies like Apple and Amazon are under siege. Prediction markets have seen a 20% spike in 'Breakup' scenarios for at least one major tech firm before the 2027 elections.",
    url: "https://www.theverge.com/tech-policy",
    source: "The Verge"
  },
  {
    id: "5",
    category: "Entertainment",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80&auto=format&fit=crop",
    title: "NASA Seeks Industry Input for SOLAR X-Ray Irradiance Sensors",
    author: "David Kim",
    date: "Feb 2, 2026",
    excerpt: "The space agency opens bidding for new sensor tech to monitor solar flares and protect satellite infrastructure.",
    fullText: "NASA has officially issued a request for information (RFI) for next-generation Solar X-Ray Irradiance Sensors. These devices are critical for 'Space Weather' monitoring, providing early warnings for solar storms that can knock out GPS, power grids, and satellite communications. The move signals a major push toward privatizing key components of solar observation infrastructure.",
    url: "https://www.nasa.gov/news-release",
    source: "NASA"
  },
  {
    id: "6",
    category: "Crypto",
    image: "/carousel/usdc-usdt.jpg",
    title: "Stablecoin Dominance: Is USDC Finally Flipping USDT?",
    author: "Alex Rivera",
    date: "Feb 1, 2026",
    excerpt: "Compliance-first stablecoins see massive growth as regulatory clarity emerges in major financial hubs.",
    fullText: "New data shows USDC market share in Europe and Singapore has reached an all-time high, narrowing the gap with Tether. As the MiCA regulation takes full effect in the EU, the 'compliance-first' approach of Circle appears to be winning over institutional liquidity. Prediction markets are currently pricing a 35% chance that USDC total supply will exceed USDT by year-end.",
    url: "https://www.circle.com/en/usdc",
    source: "Circle"
  },
  {
    id: "7",
    category: "Politics",
    image: "/carousel/tsmc.jpg",
    title: "The Geopolitics of Semiconductors: TSMC's 2nm Gamble",
    author: "Lin Wei",
    date: "Feb 7, 2026",
    excerpt: "As Taiwan prepares for next-gen chip production, global powers race to secure supply chain dominance.",
    fullText: "TSMC is accelerating its 2nm production timeline, a move that is as much political as it is technical. With the world's dependence on high-end silicon reaching critical levels, the 'silicon shield' theory is being tested. Major economies are pouring billions into domestic foundries, but analysts question if anyone can truly replicate the efficiency of the Hsinchu science park.",
    url: "https://www.bloomberg.com/technology",
    source: "Bloomberg"
  },
  {
    id: "8",
    category: "Entertainment",
    image: "/carousel/streaming.jpg",
    title: "Streaming Wars 2.0: The Return of the Bundle",
    author: "Jordan Smith",
    date: "Feb 7, 2026",
    excerpt: "Fragmented markets lead to consumer fatigue, forcing rivals into unexpected alliances.",
    fullText: "In a surprising pivot, major streaming rivals are re-bundling their services, effectively recreating the cable TV packages they once sought to destroy. Disney, Warner Bros, and Netflix have announced cross-platform subscriptions to reduce churn and combat the rising cost of content production. It's a survival move in a saturated market where attention is the scarcest resource.",
    url: "https://variety.com/v/digital",
    source: "Variety"
  },
  {
    id: "9",
    category: "Markets",
    image: "/carousel/venture-era.jpg",
    title: "Tech Consolidation: The End of the Venture Era?",
    author: "Elena Rossi",
    date: "Feb 8, 2026",
    excerpt: "As interest rates stabilize, the focus shifts from growth-at-all-costs to sustainable unit economics.",
    fullText: "The venture capital landscape is undergoing a structural shift. The era of blitzscaling fueled by cheap capital has been replaced by a rigorous focus on profitability. Large incumbents are acquiring distressed startups at a record pace, leading to a massive wave of market consolidation. Prediction markets are seeing increased volume on merger approval odds as antitrust regulators step up their game.",
    url: "https://techcrunch.com",
    source: "TechCrunch"
  }
];

// Newspaper style: bordered badges with subtle colors
const categoryColors: Record<string, { border: string; text: string; bg: string }> = {
  Crypto: { border: "border-violet-300", text: "text-violet-700", bg: "bg-white" },
  Markets: { border: "border-sky-300", text: "text-sky-700", bg: "bg-white" },
  Sports: { border: "border-orange-300", text: "text-orange-700", bg: "bg-white" },
  Entertainment: { border: "border-pink-300", text: "text-pink-700", bg: "bg-white" },
  Politics: { border: "border-sky-300", text: "text-sky-700", bg: "bg-white" },
};

export function NewsCarousel() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [flippedCards, setFlippedCards] = useState<Set<number>>(new Set());
  const [isMobile, setIsMobile] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const deckRef = useRef<HTMLDivElement>(null);

  // Track screen size for responsive distance
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const nextCard = useCallback(() => {
    setCurrentIndex((prev) => (prev + 1) % newsData.length);
  }, []);

  const prevCard = useCallback(() => {
    setCurrentIndex((prev) => (prev - 1 + newsData.length) % newsData.length);
  }, []);

  // Auto-swipe functionality
  useEffect(() => {
    // Don't auto-swipe if any card is flipped (user is reading) or if manually paused
    if (flippedCards.size > 0 || isPaused) return;

    const timer = setTimeout(() => {
      nextCard();
    }, 5000);

    return () => clearTimeout(timer);
  }, [currentIndex, flippedCards.size, isPaused, nextCard]);

  const goToCard = useCallback((index: number) => {
    setCurrentIndex(index);
  }, []);

  const toggleFlip = useCallback((index: number) => {
    if (index === currentIndex) {
      setFlippedCards((prev) => {
        const next = new Set(prev);
        if (next.has(index)) {
          next.delete(index);
        } else {
          next.add(index);
        }
        return next;
      });
    }
  }, [currentIndex]);

  // Handle auto-scroll for flipped cards
  useEffect(() => {
    const activeFlippedIndex = Array.from(flippedCards).find(idx => idx === currentIndex);
    if (activeFlippedIndex === undefined) return;

    const scrollContainer = document.getElementById(`scroll-back-${activeFlippedIndex}`);
    if (!scrollContainer) return;

    let isUserInteracting = false;
    let interactionTimer: NodeJS.Timeout;

    const handleInteraction = () => {
      isUserInteracting = true;
      clearTimeout(interactionTimer);
      // Resume auto-scroll after 5 seconds of no interaction
      interactionTimer = setTimeout(() => {
        isUserInteracting = false;
      }, 5000);
    };

    scrollContainer.addEventListener('touchstart', handleInteraction);
    scrollContainer.addEventListener('mousedown', handleInteraction);
    scrollContainer.addEventListener('wheel', handleInteraction);

    // Wait 1 second before starting the scroll
    const startTimer = setTimeout(() => {
      const scrollHeight = scrollContainer.scrollHeight;
      const clientHeight = scrollContainer.clientHeight;
      const maxScroll = scrollHeight - clientHeight;
      
      if (maxScroll <= 0) return;

      const scrollInterval = setInterval(() => {
        if (isUserInteracting) return; // Pause if user is scrolling

        if (scrollContainer.scrollTop >= maxScroll) {
          clearInterval(scrollInterval);
          return;
        }

        scrollContainer.scrollTop += 0.5; // Very slow crawl
      }, 30); // ~33fps smooth scroll

      return () => clearInterval(scrollInterval);
    }, 1000);

    return () => {
      clearTimeout(startTimer);
      clearTimeout(interactionTimer);
      scrollContainer.removeEventListener('touchstart', handleInteraction);
      scrollContainer.removeEventListener('mousedown', handleInteraction);
      scrollContainer.removeEventListener('wheel', handleInteraction);
    };
  }, [flippedCards, currentIndex]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") prevCard();
      if (e.key === "ArrowRight") nextCard();
      if (e.key === "ArrowUp") toggleFlip(currentIndex);
      if (e.key === "ArrowDown") toggleFlip(currentIndex);
      if (e.key === " ") {
        e.preventDefault();
        toggleFlip(currentIndex);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [currentIndex, nextCard, prevCard, toggleFlip]);

  // Touch/drag handling with passive: false to prevent horizontal scroll
  useEffect(() => {
    const deck = deckRef.current;
    if (!deck) return;

    let touchStartX = 0;
    let touchStartY = 0;
    let isDraggingHorizontal = false;
    let isDraggingVertical = false;

    const handleTouchStart = (e: TouchEvent) => {
      touchStartX = e.touches[0].clientX;
      touchStartY = e.touches[0].clientY;
      isDraggingHorizontal = false;
      isDraggingVertical = false;
    };

    const handleTouchMove = (e: TouchEvent) => {
      const diffX = e.touches[0].clientX - touchStartX;
      const diffY = e.touches[0].clientY - touchStartY;

      // Vertical swipe detection
      if (Math.abs(diffY) > Math.abs(diffX) && Math.abs(diffY) > 10) {
        e.preventDefault();
        isDraggingVertical = true;
      }
      // If horizontal movement is greater, prevent default to stop page scroll
      else if (Math.abs(diffX) > Math.abs(diffY) && Math.abs(diffX) > 10) {
        e.preventDefault();
        isDraggingHorizontal = true;
      }
    };

    const handleTouchEnd = (e: TouchEvent) => {
      const diffX = e.changedTouches[0].clientX - touchStartX;
      const diffY = e.changedTouches[0].clientY - touchStartY;

      if (isDraggingVertical) {
        // Swipe up or down to flip
        if (Math.abs(diffY) > 50) {
          toggleFlip(currentIndex);
        }
      }
      else if (isDraggingHorizontal) {
        // Swipe left (negative diff) = show next card
        if (diffX < -50) {
          nextCard();
        } else if (diffX > 50) {
          prevCard();
        }
      } 
      // If it was a tap (not a significant swipe or scroll)
      else if (Math.abs(diffX) < 10 && Math.abs(diffY) < 10) {
        const rect = deck.getBoundingClientRect();
        const tapX = e.changedTouches[0].clientX - rect.left;
        const centerX = rect.width / 2;
        const threshold = rect.width * 0.2; // 20% of width from center

        if (tapX < centerX - threshold) {
          prevCard();
        } else if (tapX > centerX + threshold) {
          nextCard();
        }
      }
      isDraggingHorizontal = false;
      isDraggingVertical = false;
    };

    // Add listeners with passive: false for touch events
    deck.addEventListener("touchstart", handleTouchStart, { passive: true });
    deck.addEventListener("touchmove", handleTouchMove, { passive: false });
    deck.addEventListener("touchend", handleTouchEnd, { passive: true });

    return () => {
      deck.removeEventListener("touchstart", handleTouchStart);
      deck.removeEventListener("touchmove", handleTouchMove);
      deck.removeEventListener("touchend", handleTouchEnd);
    };
  }, [nextCard, prevCard, toggleFlip, currentIndex]);

  // Mouse drag handling
  const mouseStartX = useRef(0);
  const mouseStartY = useRef(0);

  const handleMouseDown = (e: React.MouseEvent) => {
    mouseStartX.current = e.clientX;
    mouseStartY.current = e.clientY;
  };

  const handleMouseUp = (e: React.MouseEvent) => {
    const diffX = e.clientX - mouseStartX.current;
    const diffY = e.clientY - mouseStartY.current;
    
    // Vertical drag/swipe
    if (Math.abs(diffY) > 50 && Math.abs(diffY) > Math.abs(diffX)) {
      toggleFlip(currentIndex);
    }
    // If it was a horizontal drag/swipe
    else if (Math.abs(diffX) > 50) {
      if (diffX > 0) prevCard();
      else nextCard();
    } 
    // If it was a simple click, check if it was on the left or right "zones"
    else if (Math.abs(diffX) < 10 && Math.abs(diffY) < 10) {
      const rect = deckRef.current?.getBoundingClientRect();
      if (rect) {
        const clickX = e.clientX - rect.left;
        const centerX = rect.width / 2;
        // Threshold: clicking further than 100px (mobile) or 150px (desktop) from center triggers navigation
        const threshold = isMobile ? 80 : 140;

        if (clickX < centerX - threshold) {
          prevCard();
        } else if (clickX > centerX + threshold) {
          nextCard();
        }
      }
    }
  };

  const getCardStyle = (index: number) => {
    const offset = index - currentIndex;
    const total = newsData.length;

    // Handle wrapping for smooth circular navigation
    let adjustedOffset = offset;
    if (offset > total / 2) adjustedOffset = offset - total;
    if (offset < -total / 2) adjustedOffset = offset + total;

    const angleStep = 360 / total;
    const angle = adjustedOffset * angleStep;
    // Responsive distance: smaller on mobile to keep cards visible
    const distance = isMobile ? 160 : 350;

    const x = Math.sin((angle * Math.PI) / 180) * distance;
    const z = Math.cos((angle * Math.PI) / 180) * distance - distance;
    const rotateY = -angle;

    let scale = 1;
    let opacity = 1;
    let zIndex = 0;

    const absOffset = Math.abs(adjustedOffset);
    if (absOffset === 0) {
      scale = 1;
      opacity = 1;
      zIndex = 10;
    } else if (absOffset === 1) {
      scale = isMobile ? 0.85 : 0.9;
      opacity = isMobile ? 0.7 : 0.85;
      zIndex = 5;
    } else if (absOffset === 2) {
      scale = isMobile ? 0.7 : 0.8;
      opacity = isMobile ? 0.5 : 0.65;
      zIndex = 3;
    } else {
      scale = isMobile ? 0.6 : 0.7;
      opacity = isMobile ? 0.3 : 0.5;
      zIndex = 1;
    }

    return {
      transform: `translate(-50%, -50%) translateX(${x}px) translateZ(${z}px) rotateY(${rotateY}deg) scale(${scale})`,
      opacity,
      zIndex,
    };
  };

  return (
    <div 
      className="relative overflow-visible"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
      onTouchStart={() => setIsPaused(true)}
      onTouchEnd={() => {
        // Delay resuming auto-swipe after touch ends
        setTimeout(() => setIsPaused(false), 1000);
      }}
    >
      {/* Carousel Container */}
      <div
        className="relative h-[460px] sm:h-[520px] md:h-[580px] mx-auto max-w-full overflow-visible"
        style={{
          perspective: "1200px",
          touchAction: "pan-y", // Allow vertical scroll, prevent horizontal
        }}
      >
        <div
          ref={deckRef}
          className="relative w-full h-full cursor-grab active:cursor-grabbing"
          style={{ transformStyle: "preserve-3d" }}
          onMouseDown={handleMouseDown}
          onMouseUp={handleMouseUp}
        >
          {newsData.map((news, index) => {
            const style = getCardStyle(index);
            const isFlipped = flippedCards.has(index);
            const isCurrent = index === currentIndex;
            const cat = categoryColors[news.category] || { border: "border-stone-300", text: "text-stone-700", bg: "bg-white" };

            return (
              <div
                key={news.id}
                className="absolute left-1/2 top-1/2 w-[260px] h-[400px] sm:w-[320px] sm:h-[460px] md:w-[400px] md:h-[500px]"
                style={{
                  ...style,
                  transformStyle: "preserve-3d",
                  transition: "all 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
                  pointerEvents: "auto",
                  cursor: isCurrent ? "pointer" : "zoom-in",
                }}
                onClick={(e) => {
                  // Only handle flipping here if it's the current card
                  if (isCurrent) {
                    e.stopPropagation();
                  }
                }}
              >
                {/* Card Inner (handles flip) */}
                <div
                  className="relative w-full h-full"
                  style={{
                    transformStyle: "preserve-3d",
                    transition: "transform 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
                    transform: isFlipped ? "rotateX(180deg)" : "rotateX(0deg)",
                  }}
                >
                  {/* Front Face */}
                  <div
                    className="absolute inset-0 overflow-hidden bg-white border border-stone-200 flex flex-col"
                    style={{
                      backfaceVisibility: "hidden",
                      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
                    }}
                  >
                    <div className="p-5 sm:p-6 flex flex-col h-full">
                      <div className="flex justify-between items-start">
                        <span className={`px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider border ${cat.border} ${cat.text} ${cat.bg}`}>
                          {news.category}
                        </span>
                        {isCurrent && (
                          <div className="flex flex-col items-end animate-bounce">
                            <span className="text-[10px] font-bold text-[#0C4A6E]">↑ READ</span>
                          </div>
                        )}
                      </div>
                      
                      <img
                        src={news.image}
                        alt={news.title}
                        className="w-full h-36 sm:h-44 md:h-48 object-cover mt-3"
                      />
                      <h3
                        className="text-lg sm:text-xl font-serif font-semibold text-stone-900 mt-3 leading-tight"
                      >
                        {news.title}
                      </h3>
                      
                      <p className="text-[11px] sm:text-xs text-stone-600 mt-2 line-clamp-1 sm:line-clamp-2 flex-1 leading-relaxed">
                        {news.excerpt}
                      </p>
                      
                      <span className="text-[10px] text-[#0C4A6E] font-semibold mt-1">
                        Swipe up to read more →
                      </span>
                    </div>
                  </div>

                  {/* Back Face */}
                  <div
                    className="absolute inset-0 overflow-hidden bg-white border border-stone-200 flex flex-col"
                    style={{
                      backfaceVisibility: "hidden",
                      transform: "rotateX(180deg)",
                      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
                    }}
                  >
                    <div className="p-5 sm:p-6 flex flex-col h-full bg-[#FAFAF9]/50">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className={`px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider border ${cat.border} ${cat.text} bg-white`}>
                            Full Story
                          </span>
                        </div>
                        {isCurrent && (
                          <div className="flex flex-col items-end animate-bounce">
                            <span className="text-[10px] font-bold text-[#0C4A6E]">↓ BACK</span>
                          </div>
                        )}
                      </div>
                      
                      <h3
                        className="text-base sm:text-lg font-serif font-semibold text-stone-900 leading-tight mb-2 border-b border-stone-200 pb-2"
                      >
                        {news.title}
                      </h3>
                      
                      <div 
                        id={`scroll-back-${index}`}
                        className="flex-1 overflow-y-auto pr-2 custom-scrollbar scroll-smooth"
                      >
                        <p className="text-sm sm:text-base text-stone-700 leading-relaxed font-serif italic">
                          "{news.fullText}"
                        </p>
                        <a 
                          href={news.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          onClick={(e) => e.stopPropagation()}
                          className="inline-block mt-4 text-xs font-bold text-[#0C4A6E] uppercase tracking-widest border-b-2 border-[#0C4A6E] pb-0.5 hover:text-[#075985] hover:border-[#075985] transition-colors"
                        >
                          Read Full Story on {new URL(news.url).hostname.replace('www.', '')} ↗
                        </a>
                      </div>
                      
                      <div className="flex items-center justify-between mt-4 pt-4 border-t border-stone-200">
                        <div className="flex flex-col">
                          <span className="text-[10px] font-medium text-stone-400 uppercase tracking-wider">Author</span>
                          <span className="text-xs font-semibold text-stone-900">{news.author}</span>
                        </div>
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleFlip(index);
                          }}
                          className="text-xs text-[#0C4A6E] font-semibold hover:underline"
                        >
                          ← Close
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Hint text */}
      <p className="text-center text-[10px] font-medium text-stone-400 mt-4 uppercase tracking-widest">
        Swipe left/right to browse • Swipe up/down to read more
      </p>
    </div>
  );
}
